### ISSUE TITLE
"Indeed, if your language has closures, you can make yourself a μKanren." just closures?

### ISSUE THREAD

**Issue by LeeAlephium** [ashton314/muKanren_reading#1]
Does it require closures or can it use functions which take surrounding state too?

**Comment by ashton314** [comment]
I don’t understand what you mean by “functions which take surrounding state”. Could you please expound on that? Maybe give me an example of how what you’re thinking of differs from a closure?

**Comment by LeeAlephium** [comment]
```
{
  let a = 1;
  let b = 8;
  f({ a, b }) // pass state down
}
```

**Comment by ashton314** [comment]
Are you trying to show something other than just a normal function call? I think you're using the term "state" in a way that's different from how I understand it. State usually refers to some globally observable values which can be mutated in some way. (E.g. mutable variables, IO, etc.) What you've shown me could be done with a pass-by-value language (or even a pass-by-reference language with immutable data) and doesn't need to have any effect on the program state.

microKanren can be implemented (and is in the paper, as well as here) in a *pure*, side-effect free language. Any state (e.g. the fresh variable counter) is passed around explicitly and threaded throughout the entire program. Mutation or freshness (e.g. with `gensym`) can make certain parts more efficient, but they're not necessary.

You *do* need closures though to get the thunks in the result stream to work. Did that answer your question?

**Comment by ashton314** [comment]
I'm going to consider your question answered @LeeAlephium; if you would like to discuss further, please feel free to re-open.
